#datasource
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fame?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

fame:
  config:
    title: Fame博客
    description: Fame博客
    keywords: Fame,blog,博客
    send-mail: true
    mail:
      host: xxxx@qq.com
      port: 0
      username: xxxxx
      password: xxxxx
